### ISSUE TITLE
Just little refactor suggestion

### ISSUE THREAD

**Issue by joubertredrat** [castmetal/golang-api-boilerplate#1]
Hi,

In link below you have this part of code
```go
func IsDev(config config.EnvStruct) bool {
	isDev := true
	if config.Environment == "prod" {
		isDev = false
	}

	return isDev
}
```
I guess instead of this, you can use something like below
```go
func IsDev(config config.EnvStruct) bool {
	return config.Environment != "prod"
}
```
What you think, makes sense or sounds strange? :)

Reference:
https://github.com/castmetal/golang-api-boilerplate/blob/39259ad84e71c23bfaee521c9fa22f299ab7db1d/src/ports/common.go#L16C1-L23C2

**Comment by castmetal** [comment]
Great, thank you very much!
